package com.okmich.rdbmstonosql.redis.ui;

import com.okmich.rdbmstonosql.redis.ui.model.SearchFormModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michael Enudi
 */
public class DoubleItemSearchForm extends javax.swing.JPanel {

    private final SearchFormModel model;

    /**
     * Creates new form SingleItemSearchForm
     *
     * @param model
     */
    public DoubleItemSearchForm(SearchFormModel model) {
        this.model = model;
        initComponents();
        apply(false);
    }

    public void apply(boolean criteriaChanged) {
        //update the model
        String firstArg = "", secondArgs = "";
        if (cbxCriteria1.isEnabled()) {
            firstArg = cbxCriteria1.getSelectedItem().toString();
        }
        if (cbxCriteria2.isEnabled()) {
            secondArgs = cbxCriteria2.getSelectedItem().toString();
        }

        model.update(firstArg, secondArgs, criteriaChanged);

        //apply for the combo box        
        DefaultTableModel tableModel = (DefaultTableModel) this.searchResultTable.getModel();
        tableModel.setDataVector(model.tableData(), model.columnNames());

        //apply for the btn
        btnPrevious.setEnabled(model.hasPrevious());
        btnNext.setEnabled(model.hasNext());
        //total count
        lblTotalRecCount.setText(String.valueOf(model.recordCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        pnlSearchControls = new javax.swing.JPanel();
        cbxCriteria1 = new javax.swing.JComboBox<>();
        chkAllGenre = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        cbxCriteria2 = new javax.swing.JComboBox<>();
        chkAllYear = new javax.swing.JCheckBox();
        lblTotalRecCount = new javax.swing.JLabel();
        searchResultTableScrollView = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnlSearchControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        cbxCriteria1.setModel(new javax.swing.DefaultComboBoxModel<>(model.searchCriteriaArray()[0]));
        cbxCriteria1.setEnabled(model.searchCriteriaArray()[0].length > 0);
        cbxCriteria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCriteria1ActionPerformed(evt);
            }
        });
        pnlSearchControls.add(cbxCriteria1);

        chkAllGenre.setText("All");
        chkAllGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllGenreActionPerformed(evt);
            }
        });
        pnlSearchControls.add(chkAllGenre);

        jPanel1.setMinimumSize(new java.awt.Dimension(30, 10));
        pnlSearchControls.add(jPanel1);

        cbxCriteria2.setModel(new javax.swing.DefaultComboBoxModel<>(model.searchCriteriaArray()[1]));
        cbxCriteria2.setEnabled(cbxCriteria1.isEnabled());
        cbxCriteria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCriteria2ActionPerformed(evt);
            }
        });
        pnlSearchControls.add(cbxCriteria2);

        chkAllYear.setText("All");
        chkAllYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAllYearActionPerformed(evt);
            }
        });
        pnlSearchControls.add(chkAllYear);

        jPanel2.add(pnlSearchControls, new java.awt.GridBagConstraints());

        lblTotalRecCount.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        lblTotalRecCount.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.2;
        jPanel2.add(lblTotalRecCount, gridBagConstraints);

        add(jPanel2);

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        searchResultTableScrollView.setViewportView(searchResultTable);

        add(searchResultTableScrollView);

        pnlFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnPrevious.setText("  <  ");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        pnlFooter.add(btnPrevious);

        btnNext.setText("  >  ");
        btnNext.setToolTipText("");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlFooter.add(btnNext);

        add(pnlFooter);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        model.next();
        apply(false);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        model.previous();
        apply(false);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void cbxCriteria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCriteria1ActionPerformed
        apply(true);
    }//GEN-LAST:event_cbxCriteria1ActionPerformed

    private void cbxCriteria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCriteria2ActionPerformed
        apply(true);
    }//GEN-LAST:event_cbxCriteria2ActionPerformed

    private void chkAllGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllGenreActionPerformed
        cbxCriteria1.setSelectedItem("");
        cbxCriteria1.setEnabled(!chkAllGenre.isSelected());
        apply(true);
    }//GEN-LAST:event_chkAllGenreActionPerformed

    private void chkAllYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAllYearActionPerformed
        cbxCriteria2.setSelectedItem("");
        cbxCriteria2.setEnabled(!chkAllYear.isSelected());
        apply(true);
    }//GEN-LAST:event_chkAllYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox<String> cbxCriteria1;
    private javax.swing.JComboBox<String> cbxCriteria2;
    private javax.swing.JCheckBox chkAllGenre;
    private javax.swing.JCheckBox chkAllYear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTotalRecCount;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlSearchControls;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JScrollPane searchResultTableScrollView;
    // End of variables declaration//GEN-END:variables
}
