/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.rdbmstonosql.redis.ui;

import com.okmich.rdbmstonosql.redis.dao.MovieDao;
import com.okmich.rdbmstonosql.redis.ui.model.GenreDistSearchFormModel;
import com.okmich.rdbmstonosql.redis.ui.model.MovieSearchFormModel;
import java.util.Map;
import redis.clients.jedis.Jedis;

/**
 *
 * @author Michael Enudi
 */
public class MoviePanel extends javax.swing.JPanel implements MessageConsumer {

    private MovieDao dao;

    private SingleItemSearchForm genreHistSearchForm;
    private DoubleItemSearchForm movieSearchForm;

    /**
     * Creates new form RatingPanel
     *
     * @param movieDao
     */
    public MoviePanel(MovieDao movieDao) {
        this.dao = movieDao;
        this.movieSearchForm = new DoubleItemSearchForm(
                new MovieSearchFormModel(dao));
        this.genreHistSearchForm = new SingleItemSearchForm(
                new GenreDistSearchFormModel(dao));
        initComponents();

        movieByCriteriaPanel.add(this.movieSearchForm);
        genreDistPanel.add(this.genreHistSearchForm);
    }

    @Override
    public void applyMessage(Object... args) {
        this.genreHistSearchForm.apply();
        this.movieSearchForm.apply(false);
    }

    /**
     * Creates new form RatingPanel
     */
    public MoviePanel(Jedis jedis) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        movieByCriteriaPanel = new javax.swing.JPanel();
        genreDistPanel = new javax.swing.JPanel();
        newMoviePanel = new javax.swing.JPanel();
        txtMovieData = new javax.swing.JTextField();
        btnSaveMovie = new javax.swing.JButton();
        lblSummaryByIDPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMovieId = new javax.swing.JTextField();
        lblMovieDetails = new javax.swing.JLabel();
        lblSummary = new javax.swing.JLabel();
        lblSummary1 = new javax.swing.JLabel();
        lblMovieAgg = new javax.swing.JLabel();
        lblMovieScore = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        movieByCriteriaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Find Movie By Genre and Release Year"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(movieByCriteriaPanel, gridBagConstraints);

        genreDistPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Genre Dist. of Movies"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(genreDistPanel, gridBagConstraints);

        newMoviePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New Movie"));
        newMoviePanel.setLayout(new java.awt.GridBagLayout());

        txtMovieData.setColumns(25);
        newMoviePanel.add(txtMovieData, new java.awt.GridBagConstraints());

        btnSaveMovie.setText("Save");
        btnSaveMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMovieActionPerformed(evt);
            }
        });
        newMoviePanel.add(btnSaveMovie, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        add(newMoviePanel, gridBagConstraints);

        lblSummaryByIDPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Find Movie By ID"));
        lblSummaryByIDPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        lblSummaryByIDPanel.add(jLabel1, gridBagConstraints);

        txtMovieId.setColumns(7);
        txtMovieId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMovieIdKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMovieIdKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        lblSummaryByIDPanel.add(txtMovieId, gridBagConstraints);

        lblMovieDetails.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblMovieDetails.setForeground(new java.awt.Color(92, 136, 198));
        lblMovieDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovieDetails.setText("no movie found....");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 3, 1);
        lblSummaryByIDPanel.add(lblMovieDetails, gridBagConstraints);

        lblSummary.setText("Rating Summary:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        lblSummaryByIDPanel.add(lblSummary, gridBagConstraints);

        lblSummary1.setText("Rating Score:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        lblSummaryByIDPanel.add(lblSummary1, gridBagConstraints);

        lblMovieAgg.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblMovieAgg.setForeground(new java.awt.Color(92, 136, 198));
        lblMovieAgg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovieAgg.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 3, 1);
        lblSummaryByIDPanel.add(lblMovieAgg, gridBagConstraints);

        lblMovieScore.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lblMovieScore.setForeground(new java.awt.Color(92, 136, 198));
        lblMovieScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovieScore.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 3, 1);
        lblSummaryByIDPanel.add(lblMovieScore, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(lblSummaryByIDPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMovieActionPerformed
        String moviePayload = txtMovieData.getText();
        this.dao.createMovie(moviePayload);
        txtMovieData.setText("");
    }//GEN-LAST:event_btnSaveMovieActionPerformed

    private void txtMovieIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovieIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieIdKeyTyped

    private void txtMovieIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMovieIdKeyReleased
        String id = txtMovieId.getText();
        Map<String, Object> resMap = this.dao.findMovieById(id);
        if (resMap == null) {
            lblMovieDetails.setText("No movie found...");
            lblMovieAgg.setText("-");
            lblMovieScore.setText("-");
        } else {
            String agg = String.format("Count - %s, Sum - %s", resMap.get("count"), resMap.get("sum"));
            String score = String.format("Score - %.4f, Rank - %s", Double.parseDouble(resMap.get("score").toString()), resMap.get("rank"));
            lblMovieDetails.setText(resMap.get("payload").toString());
            lblMovieAgg.setText(agg);
            lblMovieScore.setText(score);
        }

    }//GEN-LAST:event_txtMovieIdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveMovie;
    private javax.swing.JPanel genreDistPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMovieAgg;
    private javax.swing.JLabel lblMovieDetails;
    private javax.swing.JLabel lblMovieScore;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblSummary1;
    private javax.swing.JPanel lblSummaryByIDPanel;
    private javax.swing.JPanel movieByCriteriaPanel;
    private javax.swing.JPanel newMoviePanel;
    private javax.swing.JTextField txtMovieData;
    private javax.swing.JTextField txtMovieId;
    // End of variables declaration//GEN-END:variables
}
