/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.rdbmstonosql.redis.ui;

import com.okmich.rdbmstonosql.redis.dao.RatingDao;
import com.okmich.rdbmstonosql.redis.ui.model.RatingsSearchFormModel;
import com.okmich.rdbmstonosql.redis.ui.model.TopNSearchFormModel;
import java.text.DecimalFormat;

/**
 *
 * @author Michael Enudi
 */
public final class RatingPanel extends javax.swing.JPanel implements MessageConsumer {

    private final RatingDao dao;

    private final SingleItemSearchForm allRatingForm;
    private final SingleItemSearchForm topNSearchForm;

    /**
     * Creates new form RatingPanel
     *
     * @param ratingDao
     */
    public RatingPanel(RatingDao ratingDao) {
        this.dao = ratingDao;
        this.allRatingForm = new SingleItemSearchForm(
                new RatingsSearchFormModel(dao));
        this.topNSearchForm = new SingleItemSearchForm(
                new TopNSearchFormModel(dao, 30));
        initComponents();

        allRatingsPanel.add(this.allRatingForm);
        leaderBoardPanel.add(this.topNSearchForm);

        refresh();
    }

    @Override
    public void applyMessage(Object... args) {
        this.allRatingForm.apply();
        this.topNSearchForm.apply();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        allRatingsPanel = new javax.swing.JPanel();
        leaderBoardPanel = new javax.swing.JPanel();
        createRatingPanel = new javax.swing.JPanel();
        txtNewRating = new javax.swing.JTextField();
        btnNewRating = new javax.swing.JButton();
        labelPanel = new javax.swing.JPanel();
        lblActiveUsersCnt = new javax.swing.JLabel();
        lblAllRatingCount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        allRatingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("All Movie Ratings"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(allRatingsPanel, gridBagConstraints);

        leaderBoardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Rating Summary Leaders Board"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(leaderBoardPanel, gridBagConstraints);

        createRatingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New Rating"));

        txtNewRating.setColumns(25);
        txtNewRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewRatingActionPerformed(evt);
            }
        });
        createRatingPanel.add(txtNewRating);

        btnNewRating.setText("Save");
        btnNewRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRatingActionPerformed(evt);
            }
        });
        createRatingPanel.add(btnNewRating);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        add(createRatingPanel, gridBagConstraints);

        labelPanel.setLayout(new java.awt.GridBagLayout());

        lblActiveUsersCnt.setFont(new java.awt.Font("Tlwg Typo", 1, 18)); // NOI18N
        lblActiveUsersCnt.setForeground(new java.awt.Color(34, 115, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        labelPanel.add(lblActiveUsersCnt, gridBagConstraints);

        lblAllRatingCount.setFont(new java.awt.Font("Tlwg Typo", 1, 18)); // NOI18N
        lblAllRatingCount.setForeground(new java.awt.Color(34, 115, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        labelPanel.add(lblAllRatingCount, gridBagConstraints);

        jLabel1.setText("Number of Ratings");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        labelPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Number of Active User");
        jLabel2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        labelPanel.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(labelPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewRatingActionPerformed
        btnNewRatingActionPerformed(evt);
    }//GEN-LAST:event_txtNewRatingActionPerformed

    private void btnNewRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRatingActionPerformed
        String payload = txtNewRating.getText();
        this.dao.createRating(payload);
        txtNewRating.setText("");
    }//GEN-LAST:event_btnNewRatingActionPerformed

    public void refresh() {
        lblActiveUsersCnt.setText(new DecimalFormat("#,##0").format(this.dao.getActiveRatingUser()));
        lblAllRatingCount.setText(new DecimalFormat("#,##0").format(this.dao.countAllRatings()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allRatingsPanel;
    private javax.swing.JButton btnNewRating;
    private javax.swing.JPanel createRatingPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JLabel lblActiveUsersCnt;
    private javax.swing.JLabel lblAllRatingCount;
    private javax.swing.JPanel leaderBoardPanel;
    private javax.swing.JTextField txtNewRating;
    // End of variables declaration//GEN-END:variables
}
