package com.okmich.rdbmstonosql.redis.ui;

import com.okmich.rdbmstonosql.redis.ui.model.SearchFormModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Michael Enudi
 */
public class SingleItemSearchForm extends javax.swing.JPanel {

    private final SearchFormModel model;

    /**
     * Creates new form SingleItemSearchForm
     * 
     * @param model
     */
    public SingleItemSearchForm(SearchFormModel model) {
        this.model = model;
        initComponents();
        apply();
    }

    public void apply() {
        //update the model 
        if (cbxCriteria.isEnabled()) {
            model.update(cbxCriteria.getSelectedItem().toString());
        } else {
            model.update();
        }
        //apply for the combo box        
        DefaultTableModel tableModel = (DefaultTableModel) this.searchResultTable.getModel();
        tableModel.setDataVector(model.tableData(), model.columnNames());

        //apply for the btn
        btnPrevious.setEnabled(model.hasPrevious());
        btnNext.setEnabled(model.hasNext());
        //total count
        lblTotalRecCount.setText(String.valueOf(model.recordCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        cbxCriteria = new javax.swing.JComboBox<>();
        lblTotalRecCount = new javax.swing.JLabel();
        searchResultTableScrollView = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        pnlFooter = new javax.swing.JPanel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        cbxCriteria.setModel(new javax.swing.DefaultComboBoxModel<>(model.searchCriteria()));
        cbxCriteria.setEnabled(model.searchCriteria().length > 0);
        cbxCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCriteriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(cbxCriteria, gridBagConstraints);

        lblTotalRecCount.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        lblTotalRecCount.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.2;
        jPanel2.add(lblTotalRecCount, gridBagConstraints);

        add(jPanel2);

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        searchResultTable.setRowSorter(new TableRowSorter<TableModel>(searchResultTable.getModel()));
        searchResultTableScrollView.setViewportView(searchResultTable);

        add(searchResultTableScrollView);

        pnlFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnPrevious.setText("  <  ");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        pnlFooter.add(btnPrevious);

        btnNext.setText("  >  ");
        btnNext.setToolTipText("");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlFooter.add(btnNext);

        add(pnlFooter);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        model.next();
        apply();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        model.previous();
        apply();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void cbxCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCriteriaActionPerformed
        apply();
    }//GEN-LAST:event_cbxCriteriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox<String> cbxCriteria;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTotalRecCount;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JScrollPane searchResultTableScrollView;
    // End of variables declaration//GEN-END:variables
}
