/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.okmich.rdbmstonosql.redis.ui;

import com.okmich.rdbmstonosql.redis.ui.model.UserByGenderSearchFormModel;
import com.okmich.rdbmstonosql.redis.ui.model.UserByAgeSearchFormModel;
import com.okmich.rdbmstonosql.redis.dao.UserDao;

/**
 *
 * @author Michael Enudi
 */
public class UserPanel extends javax.swing.JPanel implements MessageConsumer {

    private final UserDao dao;

    private final SingleItemSearchForm userByAgeForm;
    private final SingleItemSearchForm userByGenderForm;

    /**
     * Creates new form RatingPanel
     *
     * @param userDao
     */
    public UserPanel(UserDao userDao) {
        this.dao = userDao;
        this.userByAgeForm = new SingleItemSearchForm(
                new UserByAgeSearchFormModel(dao));
        this.userByGenderForm = new SingleItemSearchForm(
                new UserByGenderSearchFormModel(dao));
        initComponents();

        userByAgePanel.add(this.userByAgeForm);
        userByGenderPanel.add(this.userByGenderForm);
    }

    @Override
    public void applyMessage(Object... args) {
        this.userByAgeForm.apply();
        this.userByGenderForm.apply();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        userByAgePanel = new javax.swing.JPanel();
        userByGenderPanel = new javax.swing.JPanel();
        userByIdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        lblUserDetails = new javax.swing.JLabel();
        newUserPanel = new javax.swing.JPanel();
        txtNewUser = new javax.swing.JTextField();
        btnNewUser = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        userByAgePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("User By Age Group"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userByAgePanel, gridBagConstraints);

        userByGenderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("User By Gender"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(userByGenderPanel, gridBagConstraints);

        userByIdPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Find User by ID"));
        userByIdPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("User ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        userByIdPanel.add(jLabel1, gridBagConstraints);

        txtUserId.setColumns(7);
        txtUserId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserIdKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserIdKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        userByIdPanel.add(txtUserId, gridBagConstraints);

        lblUserDetails.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblUserDetails.setForeground(new java.awt.Color(92, 136, 198));
        lblUserDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserDetails.setText("no user found....");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.insets = new java.awt.Insets(1, 2, 3, 1);
        userByIdPanel.add(lblUserDetails, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(userByIdPanel, gridBagConstraints);

        newUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("New User"));
        newUserPanel.setLayout(new javax.swing.BoxLayout(newUserPanel, javax.swing.BoxLayout.PAGE_AXIS));

        txtNewUser.setColumns(20);
        txtNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewUserActionPerformed(evt);
            }
        });
        newUserPanel.add(txtNewUser);

        btnNewUser.setText("Save");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });
        newUserPanel.add(btnNewUser);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(newUserPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdKeyTyped

    private void txtUserIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIdKeyReleased
        String id = txtUserId.getText();
        String userDetails = this.dao.findUserById(id);
        if (userDetails == null)
            lblUserDetails.setText("No user found...");
        else
            lblUserDetails.setText(userDetails);
    }//GEN-LAST:event_txtUserIdKeyReleased

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        String userDetails = txtNewUser.getText();
        dao.createUser(userDetails);
        txtNewUser.setText("");
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void txtNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewUserActionPerformed
        btnNewUserActionPerformed(evt);
    }//GEN-LAST:event_txtNewUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUserDetails;
    private javax.swing.JPanel newUserPanel;
    private javax.swing.JTextField txtNewUser;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JPanel userByAgePanel;
    private javax.swing.JPanel userByGenderPanel;
    private javax.swing.JPanel userByIdPanel;
    // End of variables declaration//GEN-END:variables
}
